### PR TITLE
 add trust=skip to skip client certificate check

### PR DESCRIPTION
**Pull request by kdomanski**

### CODE REVIEW

**Comment by pbeckingham** [comment]
I don't know what the rationale behind any of these changes is.  I don't think kipping cert checking is a good idea.  Please explain.

Patch also contains zero documentation updates, which would be required.

**Comment by kdomanski** [comment]
The PR is somewhat related to GothenburgBitFactory/taskwarrior/pull/2040 
It allows to depend only on the credentials passed by the client in order to authenticate the user. The behavior does not become default.

**Comment by pbeckingham** [comment]
Alright, I'm sold . These are good changes.

**Comment by kdomanski** [comment]
So how about a merge then? ;)

**Comment by pbeckingham** [comment]
Is the documentation updated yet, as requested in the PR?

**Comment by kdomanski** [comment]
Updated the man page.

**Pull request closed without merging**
